### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by mottosso** [abstractfactory/maya-capture#20]
Here's some reference for a potential GUI, from Softimage.

![image](https://cloud.githubusercontent.com/assets/2152766/9106399/f05fe56c-3c17-11e5-8fa9-e02607b4c93d.png)

The colors and layout is not to be followed, but rather some of it's properties.

Key properties.

1. An output path, with a browser
2. Choice of format, with options
3. Output resolution, defaulted to either previous or render settings
4. Start and End frame
5. FPS
4. Anti-alias
5. Play when finished

Added properties.

1. In- or off-screen
2. Warn when larger than screen, suggest off-screen
3. Viewport options, such as which renderer to use
4. Renderer options, such as motion blur
5. Panel settings, such as which nodes to filter out or isolate

**Comment by BigRoy** [comment]
Nice reference.

I was thinking about maybe even enabling it as a *dockable* interface. This way it could remain open for an artist alongside the channelBox or attribute editor so they can perform quick playblasts with the same settings.

I'll have a look at implementing a version with PySide soon. Separate repository I presume?

**Comment by BigRoy** [comment]
Also, the playblast command seems to suffer from an undo bug, see [here](http://forums.cgsociety.org/showthread.php?f=89&t=1296751). It seems to undo back to frame one afterwards.

A hack is to use `maya.cmds.currentTime(maya.cmds.currentTime(q=1))` in front of it. For example:

```python
import maya.cmds as mc

def list_formats():
    import maya.cmds
    
    # Workaround for Maya playblast bug where undo would
    # move the currentTime to frame one.
    maya.cmds.currentTime(maya.cmds.currentTime(q=1))
    
    return maya.cmds.playblast(query=True, format=True)


def list_compressions(format='avi'):
    import maya.mel
    
    # Workaround for Maya playblast bug where undo would
    # move the currentTime to frame one.
    maya.cmds.currentTime(maya.cmds.currentTime(q=1))
    
    cmd = 'playblast -format "{0}" -query -compression'.format(format)
    return maya.mel.eval(cmd)
    
print list_formats()
```

**Comment by mottosso** [comment]
> I'll have a look at implementing a version with PySide soon. Separate repository I presume?

Yeah, better keep it separate.

> I was thinking about maybe even enabling it as a dockable interface. 

Why not. Personally I haven't had any particularly good experiences with dockable interfaces and rarely if ever use them myself, but if it doesn't harm the visuals of the undocked version then it sounds like just a toggle.

> Also, the playblast command seems to suffer from an undo bug

Separate issue please.

**Comment by BigRoy** [comment]
In that reference GUI from softimage what does altering the frame-rate actually do?

If a scene is animated 25 FPS and you would do a 30 FPS capture of 5 seconds of animation. What happens?

Does it influence solely "movie" formats that embed the frame rate ? For example do 100 frames as images on any FPS result in the same image sequence, as it only samples the Nth frame?

**Comment by mottosso** [comment]
> Does it influence solely "movie" formats that embed the frame rate ?

That's right. The outputted Quicktime file will have an embedded frame rate that players will use to determine which rate to play the images at. It's not relevant to still images or image sequences.

**Comment by BigRoy** [comment]
Great, that's what I expected. The player solely changing it at a different rate changing the speed of the animation.

**Comment by mottosso** [comment]
As the number of potential GUIs are increasing, I'll boot up a new repo dedicated to GUIs in order to keep this project small and nimble.

Making a separate capture gui repo would keep thing separate and enable advanced implementation, but then alsp make it less appealing for simple use. One can no longer drop the code into your codebase and see it work.

Its a fair compromise.

We'll keep core functionality within capture.py, and build a separate capture-gui for interfaces.

**Comment by mottosso** [comment]
An idea for a minimalistic yet useful gui.

![image](https://cloud.githubusercontent.com/assets/2152766/13898547/e9c6b3ae-edcc-11e5-8ea1-456c960f01b9.png)

```python
import os
import tempfile
from PySide import QtGui

import capture


class Window(QtGui.QDialog):
    def __init__(self, parent=None):
        super(Window, self).__init__(parent)

        preview = QtGui.QLabel()
        button = QtGui.QPushButton("Capture")
    
        layout = QtGui.QVBoxLayout(self)
        layout.addWidget(preview)
        layout.addWidget(button)

        self.preview = preview

    def refresh(self):
        tempdir = tempfile.mkdtemp()
        outname = os.path.join(tempdir, "temp.png")
        fname = capture.capture(
            width=1280 / 2,
            height=720 / 2,
            complete_filename=os.path.join(tempdir, "temp.jpg"),
            format="image",
            compression="jpg",
            frame=cmds.currentTime(query=True),
            viewer=False,
            off_screen=True)
        
        image = QtGui.QPixmap(fname)
        self.preview.setPixmap(image)
        os.remove(fname)


window = Window()
window.refresh()
window.show()

```

**Comment by BigRoy** [comment]
I've been working a bit on a capture gui (basically redoing an internal UI we had going and exposing some of the capture options).

![capture_gui](https://cloud.githubusercontent.com/assets/2439881/18607461/902bd014-7ccd-11e6-8523-58799cd5fd21.png)

The individual sections, like camera, resolution, codec are all their own "options plugin" that are added to the overall App. This also allows for a studio to add on their own widget and the options to be used during the capture.

Aside from that the capturing emits signal before playblast, after playblast and just before opening the viewer. The last one is something we'd potentially use internally at our studio to encode a custom overlay (with ffmpeg) and then after the extra encoding open the viewer.

It's a rather draft setup, e.g. UI can be somewhat cleaner, but it shows a potential direction for a capture gui.

**Comment by mottosso** [comment]
I like it.

> Not sure if Qt signals will work for that since I'm not sure they actually wait for the callback to finish. But the idea is to implement something that allows this to work.

There's an option to do this when you connect.

```python
my_widget.clicked.connect(my_callback, QtCore.Qt.DirectConnection)
```

If there is one thing I'm missing in every capture GUI I've seen, that's a preview of what it's about to do.

![image](https://cloud.githubusercontent.com/assets/2152766/18607675/72d08818-7ccb-11e6-9e4d-18a4a7eabe07.png)

That way you could immediately spot whether you accidentally had something selected, whether you've got the right camera, and whether the settings are what you'd like them to be. And you don't have to wait for it to finish to find out.

The way I would see it work technically is, when you open the dialog, it would run a capture on 1 frame with the current settings and paste it into the window. Whenever you change an option or change the frame, it would update.

**Comment by BigRoy** [comment]
I opened up a repo: https://github.com/BigRoy/maya-capture-gui

_Note that it's using Qt.py so you'll need that._

> If there is one thing I'm missing in every capture GUI I've seen, that's a preview of what it's about to do.

This is implemented in the repo. It updates upon setting changes (for camera). You can force an update clicking on the preview image.

Keep in mind it's an experimental UI for now.

**Comment by mottosso** [comment]
> Note that it's using Qt.py so you'll need that.

I think you should vendor it.

> This is implemented in the repo. 

Oh that's cool! How does it look?

**Comment by BigRoy** [comment]
Very similar to your example. ;)

![capture_gui_preview](https://cloud.githubusercontent.com/assets/2439881/18608754/4f21cf36-7cf2-11e6-99c8-273e61c90ab5.png)

I'll vendor Qt.py!

**Comment by mottosso** [comment]
Ooooh so nice!

**Comment by mottosso** [comment]
Let's consider this issue resolved, and continue discussion in your repo?

**Comment by BigRoy** [comment]
Let's!
