### ISSUE TITLE
Capturing brings up a viewport message regarding DOF

### ISSUE THREAD

**Issue by BigRoy** [abstractfactory/maya-capture#33]
The new additions for options in #1 that got merged with #31 introduced a possible viewport message in Maya 2016 (when in-view messages are set as enabled). If disabled the in-view message is not shown.

Note that it's not a show-stopping issue. It's just somewhat odd behavior to see occur, as such it's good to discuss solutions.

### Problem

This behavior comes from the fact that `capture` now also applies default settings to the depth of field (disabling it) whereas before it ignored (or basically didn't know about) those settings.

Enabling/disabling this behavior is a matter of setting some `optionVar` settings:

```
optionVar -iv inViewMessageEnable false;control -edit -enable false prefsInViewMessageAssistEnable;control -edit -enable false prefsInViewMessageStatusEnable;control -edit -enable false prefsInViewMessageDisplayTime;control -edit -enable false prefsInViewMessageFontSize;control -edit -enable false prefsInViewMessageOpacity;
```

Above is the single line of MEL code Maya runs to disable the in-view messages.

### Solution

It would be a matter of adding another context manager that ensure the setting is temporarily disabled so these pop-ups do not occur.

**Comment by mottosso** [comment]
How do I reproduce this problem?

**Comment by BigRoy** [comment]
Turn this on: `Settings/Preferences > Interface > Help > In-View Messages > Enable`.

Then running any form of `capture` would briefly show a "yellow viewport message" after the playblast.

**Comment by BigRoy** [comment]
Also note that these *in-view messages* are enabled by default on a clean install of Maya 2016.

Were you able to reproduce this behavior?

**Comment by BigRoy** [comment]
Just to note: I think this is also a 2015 or 2016 feature so when a fix is implemented care has to be taken regarding backwards compatibility.

**Comment by BigRoy** [comment]
So this fixes it in 2016:

```python

import capture
import contextlib
import maya.cmds as cmds


@contextlib.contextmanager
def disabled_inview_messages():
    """Disable in-view help messages during the context"""
    original = cmds.optionVar(q="inViewMessageEnable")
    cmds.optionVar(iv=("inViewMessageEnable", 0))
    try:
        yield
    finally:
        cmds.optionVar(iv=("inViewMessageEnable", original))


with disabled_inview_messages():
    capture.capture()
```

Since this is purely `optionVars` it should also work fine in older versions. We then just need to ensure the optionVar value gets created if it didn't exist. (Or just ignore if it didn't exist to begin with?)

Don't have older versions installed anymore so if anyone could test this pre-2016 thanks!

**Comment by BigRoy** [comment]
Actually it seems that if a value didn't exist and you just query it that it would return `0`. As such even for older versions the above should just get an original `0` value, then set `0` and revert to `0`. No harm done and should work fine if `optionVar` behaved like that in older versions as well.
