### ISSUE TITLE
Missing some ViewportOptions keys

### ISSUE THREAD

**Issue by BigRoy** [abstractfactory/maya-capture#69]
# Problem

Having a quick look over the documentation I noticed some visibility options for the viewport to be missing, specifically the `imagePlane`, `planes`, `controlVertices` and `hulls` arguments for the `modelEditor` command are lacking in the `ViewportOptions` dictionary.

I noticed the absence of some of these because image planes happened to be always visible instead of adhering to the settings when combined with a `parse_view()`.

> The "missing ones" mentioned here have been available since Maya 2014: http://download.autodesk.com/global/docs/maya2014/en_us/CommandsPython/modelEditor.html

> Note: In 2017 for example you also have `pluginShapes` argument which is not around back in 2014. I'm not sure how far we want to be backwards compatible, but adding in newer keys might hurt older versions.

Not having these keys in the `ViewportOptions` dictionary also means they won't be parsed correctly with `parse_view` or alike.

# Solution

For now I'd propose to _at least_ have all flags that were in Maya since 2014 (or whatever version we choose as oldest official supported) _or_ have the querying of applying happen in a _try-except_ fashion.

**Comment by mottosso** [comment]
I think I smell a PR!

**Comment by BigRoy** [comment]
Sure is now!

Also, as side note, the reason they seem randomly inserted is because I tried to adhere to the same order as they were listed in the `maya.cmds.modelEditor` documentation just so it was easier to see if any were still missing.
