### ISSUE TITLE
Missing frame padding argument for capture

### ISSUE THREAD

**Issue by BigRoy** [abstractfactory/maya-capture#70]
# Problem

The `capture` command is missing the option to customize the amount of frame padding for resulting image sequences. `maya.cmds.playblast` supports it with the [framePadding](http://download.autodesk.com/us/maya/2011help/CommandsPython/playblast.html#flagframePadding) argument.

> This is only relevant when playblasting to the `image` codec format.

# Solution

Add it. 😀 We can support `framePadding` by adding a `frame_padding` argument to `capture`

**Comment by BigRoy** [comment]
Forgot to reference it in the commit. So linking here: https://github.com/BigRoy/maya-capture/commit/bc7ecb6eb8be5a870f8e8cb5e8c53bd5f166442b

**Comment by mottosso** [comment]
Was there a PR coming up?

**Comment by BigRoy** [comment]
Implemented with #71
